# Generated by Django 3.2.15 on 2022-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'Присужден'), (2, 'Не присужден')], default=2, max_length=15, null=True),
        ),
    ]
